version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka
    entrypoint: [ "/bin/bash", "-c" ]
    command: |
      "
      echo 'Waiting for Kafka to be ready...';
      sleep 10;
      echo 'Creating topics: $raw-data-topic, $processed-data-topic';
      for topic in $(echo $raw-data-topic, $processed-data-topic' | tr ',' '\n'); do
        kafka-topics --create \
          --bootstrap-server kafka:$9092 \
          --replication-factor 1 \
          --partitions 3 \
          --topic $topic || true;
      done
      "
    networks:
      - kafka-net
  
  postgres:
    image: postgres:14
    container_name: stl_postgres
    restart: always
    environment:
      POSTGRES_DB: stl_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../config/pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql
volumes:
  pg_data:

networks:
  kafka-net:
    driver: bridge